### ISSUE TITLE
华为混合推送接入报重复包

### ISSUE THREAD

**Issue by zhouwangzhen** [leancloud/mixpush-demos#2]
implementation ('cn.leancloud:storage-android:6.0.4'){
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
    }
    //混合推送需要的包
    implementation('cn.leancloud:mixpush-android:6.0.4@aar') {
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
        exclude group: 'cn.leancloud', module:'huawei-hmsagent'
    }
    //即时通信与推送需要的包
    implementation ('cn.leancloud:realtime-android:6.0.4'){
        exclude group: 'com.alibaba', module: 'fastjson'
        exclude group: 'org.ligboy.retrofit2', module: 'converter-fastjson'
    }
    implementation 'com.alibaba:fastjson:1.1.70.android'
    implementation "org.ligboy.retrofit2:converter-fastjson-android:2.1.0"
    // 华为推送
    implementation 'com.huawei.android.hms:push:2.6.3.306'

在已经去掉com.huawei.android.hms:base:2.6.3.306的情况下报重复包错误
> Duplicate class com.huawei.hianalytics.a.a found in modules HiAnalyticsSDK_2.1.4.301.jar (com.huawei.android.hms:base:2.6.3.306) and hmssdk-2.6.3.306.jar (cn.leancloud:mixpush-android:6.0.4)
Duplicate class com.huawei.hianalytics.a.b found in modules HiAnalyticsSDK_2.1.4.301.jar (com.huawei.android.hms:base:2.6.3.306) and hmssdk-2.6.3.306.jar (cn.leancloud:mixpush-android:6.0.4)
....

**Comment by weakish** [comment]
duplicated by leancloud/java-unified-sdk#79
